[kanagawa]
fujiWhite = "#DCD7BA"     #Default foreground
oldWhite = "#C8C093"      #Dark foreground (statuslines)
sumiInk0 = "#16161D"      #Dark background (statuslines and floating windows)
sumiInk1 = "#1F1F28"      #Default background
sumiInk2 = "#2A2A37"      #Lighter background (colorcolumn, folds)
sumiInk3 = "#363646"      #Lighter background (cursorline)
sumiInk4 = "#54546D"      #Darker foreground (line numbers, fold column, non-text characters), float borders
waveBlue1 = "#223249"     #Popup background, visual selection background
waveBlue2 = "#2D4F67"     #Popup selection background, search background
winterGreen = "#2B3328"   #Diff Add (background)
winterYellow = "#49443C"  #Diff Change (background)
winterRed = "#43242B"     #Diff Deleted (background)
winterBlue = "#252535"    #Diff Line (background)
autumnGreen = "#76946A"   #Git Add
autumnRed = "#C34043"     #Git Delete
autumnYellow = "#DCA561"  #Git Change
samuraiRed = "#E82424"    #Diagnostic Error
roninYellow = "#FF9E3B"   #Diagnostic Warning
waveAqua1 = "#6A9589"     #Diagnostic Info
dragonBlue = "#658594"    #Diagnostic Hint
fujiGray = "#727169"      #Comments
springViolet1 = "#938AA9" #Light foreground
oniViolet = "#957FB8"     #Statements and Keywords
crystalBlue = "#7E9CD8"   #Functions and Titles
springViolet2 = "#9CABCA" #Brackets and punctuation
springBlue = "#7FB4CA"    #Specials and builtin functions
lightBlue = "#A3D4D5"     #Not used
waveAqua2 = "#7AA89F"     #Types
springGreen = "#98BB6C"   #Strings
boatYellow1 = "#938056"   #Not used
boatYellow2 = "#C0A36E"   #Operators, RegEx
carpYellow = "#E6C384"    #Identifiers - highlight
sakuraPink = "#D27E99"    #Numbers
waveRed = "#E46876"       #Standout specials 1 (builtin variables)
peachRed = "#FF5D62"      #Standout specials 2 (exception handling, return)
surimiOrange = "#FFA066"  #Constants, imports, booleans
katanaGray = "#717C7C"    #Deprecated

[kanagawa-pywal]
color0 = "#090618"
color1 = "#C34043"
color2 = "#76946A"
color3 = "#C0A36E"
color4 = "#7E9CD8"
color5 = "#957FB8"
color6 = "#6A9589"
color7 = "#C8C093"
color8 = "#727169"
color9 = "#E82424"
color10 = "#98BB6C"
color11 = "#E6C384"
color12 = "#7FB4CA"
color13 = "#938AA9"
color14 = "#7AA89F"
color15 = "#DCD7BA"
color16 = "#FFA066"
color17 = "#FF5D62"
foreground = "#DCD7BA"
background = "#1F1F28"
cursor = "#C8C093"
